### ISSUE TITLE
[batch-processing] Load of corrupted ACMI pause the process

### ISSUE THREAD

**Issue by Couby** [RaiaSoftwareInc/tacview.add-ons.lua#1]
Hi @BuzyBee1983 ,

Many thanks for this add-on !

I'm integrating it to my own add-on in order to produce some statistics from ACMIs recorded on our DCS [VEAF server](http://www.veaf.org).

I'm facing two issues (I'll open a second issue for the second one).

The first issue is the batch process is paused when loading a corrupted ACMI file (maybe because of DCS server crash).

![acmi_load_crash](https://user-images.githubusercontent.com/4526037/71554843-fbce1e00-2a24-11ea-8631-1f107233da6e.png)

Analysing more than 1000 ACMIs the process takes time so there is a real need overriding this pause.

I'm not sure we can directly fix the problem via the addon script. Maybe this is directly the load file function which should not produce this message if we don't want it. If you can check with @Vyrtuoz :blush: .

Many thanks again for this really useful script.

**Comment by Vyrtuoz** [comment]
Good point! I will make sure that Telemetry.Load() does not display any error message in the next 1.8.2 beta.

**Comment by Couby** [comment]
Many thanks @Vyrtuoz 👍 😄 .
This issue is fixed in 1.8.2 beta 5.
