### ISSUE TITLE
[batch-processing] ACMI folder/names with special characters

### ISSUE THREAD

**Issue by Couby** [RaiaSoftwareInc/tacview.add-ons.lua#2]
ACMI folder/names with special characters are either not analysed, like these ones (the 3 lasts) :
![acmi_special_characters_1](https://user-images.githubusercontent.com/4526037/71555037-5c5e5a80-2a27-11ea-9824-2bab6bc6cfc9.png)

Or produce an error/pause in the process : 
![acmi_special_characters_2](https://user-images.githubusercontent.com/4526037/71555042-68e2b300-2a27-11ea-9560-57d6bb2b9304.png)
![acmi_special_characters_3](https://user-images.githubusercontent.com/4526037/71555046-6b450d00-2a27-11ea-83cf-5c69e5bdbfc1.png)

As we have pilots from all over the world visiting our server :blush: I need to find a way to analyse their ACMIs whatever the characters they use for their nicknames 😄 .

**Comment by Vyrtuoz** [comment]
I believe this is a bug between UTF-8 (Lua) and UTF-16 (Tacview 1.x) characters conversion. I am going to fix that in the next 1.8.2 beta.

**Comment by Couby** [comment]
Also fixed in 1.8.2 beta 5 :+1: .
Files now are analysed. You rock 😎 .

**Comment by Vyrtuoz** [comment]
Thank you. It was a limitation of the lfs library: I did not support UTF-8/16 on Windows systems. I have added the feature to the file enumeration functions only. I will fix other functions on request.
